# dbt_project.yml
name: 'dbt_'
version: '1.0.0'

# dbt profile
profile: 'dbt_'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_:

    # --------------------------
    # Staging layer
    # --------------------------
    staging:
      +materialized: view
      +schema: staging

    # --------------------------
    # Marts layer
    # --------------------------
    marts:
      +materialized: table
      +schema: marts

    # --------------------------
    # Analytics layer
    # --------------------------
    analytics:
      +materialized: table
      +schema: analytics
